import os
import json
from openai import OpenAI
from dotenv import load_dotenv

# Load environment variables for the API key
load_dotenv()

# Initialize the OpenAI client
# Ensure OPENAI_API_KEY is set in your .env file
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))


# ==========================================
# 这一部分是为了从 chunks 当中提炼出可以进行逻辑计算的一段信息
# ==========================================

def load_eden_knowledge_base(filepath: str) -> dict:
    """
    Loads the structured JSON file exported by Eden's data pipeline.
    
    Args:
        filepath: Absolute or relative path to the *_rag_context.json file.
        
    Returns:
        The 'sections_data' dictionary containing sections and their respective chunks.
    """
    if not os.path.exists(filepath):
        raise FileNotFoundError(f"Cannot find Eden's data file at: {filepath}")
        
    with open(filepath, "r", encoding="utf-8") as f:
        full_data = json.load(f)
        
    # 只拿核心数据 blueprint_data- outline sections_data- chunks
    return full_data.get("blueprint_data", {}).get("sections_data", {})

def generate_section_summary(section_name: str, chunks: list, top_k: int = 3) -> str:
    """
    Calls the gpt-5.4-mini API to compress multiple fragmented chunks into 
    a single cohesive summary for NLI processing.
    
    Args:
        section_name: The title of the Wikipedia section (e.g., 'Geology').
        chunks: The list of chunk dictionaries retrieved from Tavily.
        top_k: Number of top-ranked chunks to use for the summary.
        
    Returns:
        A cohesive summary string generated by the LLM.
    """
    if not chunks:
        return ""

    # 1.获取分值最高的前 K 个文本块并concatenate
    # Eden's pipeline already sorts them by retrieval_score descending
    top_chunks = chunks[:top_k]
    combined_raw_text = "\n\n".join([c["text"] for c in top_chunks])
    
    # 2. Construct the prompt for the Summary Agent
    system_prompt = (
        "You are an expert technical summarizer. "
        "Your task is to synthesize the provided fragmented documents into a single, "
        "cohesive, and logically structured paragraph. Focus purely on factual data."
    )
    
    user_prompt = (
        f"Topic Section: {section_name}\n"
        f"Source Documents:\n{combined_raw_text}\n\n"
        f"Please provide a dense, cohesive summary of these documents."
    )

    # 3. Execute the API request to gpt-5.4-mini
    try:
        response = client.chat.completions.create(
            model="gpt-5.4-mini",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            temperature=0.3, # Low temperature for factual consistency
            max_tokens=250
        )
        return response.choices[0].message.content.strip()
        
    except Exception as e:
        print(f"[API Error] Failed to generate summary for {section_name}: {e}")
        return ""

def process_all_summaries(json_filepath: str) -> dict:
    """
    Main orchestration function to read Eden's data and generate summaries 
    for all available sections.
    """
    print(f"Loading data from: {json_filepath}")
    sections_data = load_eden_knowledge_base(json_filepath)
    
    final_summaries = {}
    
    for section, data in sections_data.items():
        print(f"Processing summary for section: {section}...")
        chunks = data.get("chunks", [])
        
        summary = generate_section_summary(section, chunks)
        final_summaries[section] = summary
        
    return final_summaries

# Execution Block for Testing
if __name__ == "__main__":
    # Adjust this path based on your actual data directory
    test_filepath = os.path.join("..", "data", "Nishinoshima_rag_context.json")
    
    # Generate the actual summaries
    summaries_dict = process_all_summaries(test_filepath)
    
    print("\n--- Final Summaries Ready for NLI Calculation ---")
    for sec, summ in summaries_dict.items():
        print(f"\n[{sec}]\n{summ}")

# ==========================================
# 开始计算逻辑关系 进行排序
# ==========================================

import networkx as nx
from sentence_transformers import CrossEncoder

# ==========================================
# Agent 2: Logic & Graph Algorithm Engineering
# ==========================================

class Agent2Orchestrator:
    def __init__(self, threshold=0.6):
        # Using a Cross-Encoder for high-accuracy NLI entailment scores
        self.model = CrossEncoder('cross-encoder/nli-deberta-v3-base')
        self.threshold = threshold

    def get_execution_plan(self, summaries_dict: dict):
        """
        Calculates dependencies and sorts sections via DAG.
        """
        sections = list(summaries_dict.keys())
        summaries = list(summaries_dict.values())
        
        # Create a Directed Graph
        dag = nx.DiGraph()
        dag.add_nodes_from(sections)

        # 1. Nested loop to compare every section pair (Asymmetric)
        # We check if Section A entails Section B
      
        # enumerate(sections): 这个函数会同时返回列表中每个元素的索引 (i) 和内容 (sec_a)
        # sections 是 ["Geology", "Ecology", "Tourism"]，那么第一轮循环 i 就是 0，sec_a 就是 "Geology"
        for i, sec_a in enumerate(sections):
            # 它选定另一个章节作为**“结论 (Conclusion)”**
            for j, sec_b in enumerate(sections):
                if i == j:
                    continue
                
                # Model predicts probabilities for [Contradiction, Neutral, Entailment]
                # We focus on index 2 (Entailment score)
                # summaries[i] 被视为 前提 (Premise) 
                # summaries[j] 被视为 假设 (Hypothesis)
                scores = self.model.predict([(summaries[i], summaries[j])])
              
                # scores[2] 是3 个概率值 里面的 Entailment 
                entailment_score = scores[2] 

                # 2. Threshold Filtering Logic
                # Only add a dependency edge if the score is high enough
                if entailment_score > self.threshold:
                    dag.add_edge(sec_a, sec_b)
                    print(f"[Dependency Found] {sec_a} -> {sec_b} (Score: {entailment_score:.2f})")

        # 3. Resolve potential cycles to ensure it's a DAG
        # If a cycle exists (A->B and B->A), we break it by removing the weaker edge
        while not nx.is_directed_acyclic_graph(dag):
            cycle = nx.find_cycle(dag)
            # Logic: Remove the edge in the cycle with the lowest entailment score
            # (Simplified for this example: just removing one edge to break the cycle)
            dag.remove_edge(cycle[0][0], cycle[0][1])

        # 4. Topological Sorting
        # This converts the DAG into a linear generation order
        execution_order = list(nx.topological_sort(dag))
        dependency_map = {}
        for node in dag.nodes():
            # predecessors(node) 会找到所有指向该章节的“前置章节”
            dependency_map[node] = list(dag.predecessors(node))
            
        # 修改返回值，把顺序和依赖表一起打包传出
        return {
            "execution_order": execution_order,
            "dependency_map": dependency_map
        }
        return execution_order

# Integration Test

if __name__ == "__main__":
    # Assuming summaries_dict is the output from your previous code
    sample_summaries = {
        "Geology": "The island's foundation is formed by volcanic basalt...",
        "Ecology": "New plant species thrive on the nutrient-rich volcanic soil...",
        "Tourism": "Visitors flock to see the active volcanic craters..."
    }

    orchestrator = Agent2Orchestrator(threshold=0.6)
    final_order = orchestrator.get_execution_plan(sample_summaries)

    print("\n--- Final Section Generation Order ---")
    print(final_order)

