llm:
  temperature: 0.0
  max_tokens: 4096
  method0:
    # provider: "openai"
    # model: "gpt-5.4-mini"
    provider: "groq"
    model: "openai/gpt-oss-20b"
  method1:
    # provider: "openai"
    # model: "gpt-5.4-mini"
    provider: "groq"
    model: "openai/gpt-oss-20b"
  method2:
    provider: "openai"
    model: "gpt-5.4-mini"
  agent2:
    # 第一部分：负责将 Chunks 压缩为 Summary 的大语言模型
    llm:
      provider: "openai"
      model: "gpt-5.4-mini"
      temperature: 0.3      
      max_tokens: 250
    # 第二部分：负责计算蕴含概率与构建图谱的专用逻辑模块
    graph_logic:
      nli_model:
        provider: "huggingface"
        model_name: "cross-encoder/nli-deberta-v3-base"
        entailment_index: 1
      algorithm:
        threshold: 0.6
        allow_cycles: false
  agent3:
    provider: "openai"
    model: "gpt-5.4-mini"
  agent4:
    provider: "openai"
    model: "gpt-5.4-mini"

api_keys:
  openai_env: "OPENAI_API_KEY"
  groq_env: "GROQ_API_KEY"

retrieval:
  tavily:
    max_results: 10      # Tavily initially retrieves a large number of chunks (e.g., 100) and then we take the top N (e.g., 8) for reranking
    search_depth: "advanced"
  
  chunking:
    chunk_size: 500     # chunking limit (number of characters per chunk)
    overlap: 60         # chunk overlap (number of characters that overlap between consecutive chunks)

  rerank:
    top_l: 8     # number of chunks kept after reranking

pipeline_config:
  target_entity: "Surtsey"
  api_key_env_var: "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"
